media:
  input: public/assets
  output: /assets
  categories: ["image"]

content:
  # =============================
  # Hero Section
  # =============================
  - name: hero
    label: Hero Section
    type: file
    path: content/pages/hero.md
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: backgroundImage, label: Background Image, type: image }
      - name: cta
        label: CTA Button
        type: object
        fields:
          - { name: label, label: Button Label, type: string }
          - { name: url, label: Redirect URL, type: string }

  # =============================
  # Blogs Section
  # =============================
  - name: blogs
    label: Blogs
    type: collection
    path: content/blogs
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover Image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: body
        label: Body
        type: rich-text
