media:
  input: public/assets
  output: /assets
  categories: ["image"]

content:
  # =============================
  # Home Page (with all sections)
  # =============================
  - name: home
    label: Home Page
    type: file
    path: content/pages/home.md
    fields:
      # Hero Section
      - name: hero
        label: Hero Section
        type: object
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: description, label: Description, type: text }
          - { name: backgroundImage, label: Background Image, type: image }
          - name: cta
            label: CTA Button
            type: object
            fields:
              - { name: label, label: Button Label, type: string }
              - { name: url, label: Redirect URL, type: string }

      # Features Section
      - name: features
        label: Features Section
        type: list
        itemLabel: title
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: description, label: Description, type: text }
          - { name: image, label: Image, type: image }
          - name: cta
            label: CTA Button
            type: object
            fields:
              - { name: label, label: Button Label, type: string }
              - { name: url, label: Redirect URL, type: string }

      # Blogs Section
      - name: blogs
        label: Blogs Section
        type: list
        itemLabel: title
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: excerpt, label: Excerpt, type: string }
          - { name: coverImage, label: Cover Image, type: image }
          - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
          - name: author
            label: Author
            type: object
            fields:
              - { name: name, label: Name, type: string }
              - { name: picture, label: Picture, type: image }
          - name: body
            label: Body
            type: rich-text

      # Subscription Section
      - name: subscription
        label: Subscription Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: description, label: Description, type: text }
          - name: form
            label: Subscription Form
            type: object
            fields:
              - { name: placeholder, label: Input Placeholder, type: string }
              - { name: buttonLabel, label: Button Label, type: string }
              - { name: actionUrl, label: Form Action URL, type: string }

      # Footer Section
      - name: footer
        label: Footer Section
        type: object
        fields:
          - { name: copyright, label: Copyright Text, type: string }
          - name: links
            label: Links
            type: list
            itemLabel: label
            fields:
              - { name: label, label: Label, type: string }
              - { name: url, label: URL, type: string }
